openapi: 3.0.0
info:
  title: ClinGen Allele Registry wrapper
  description: >-
    Wraps the ClinGen Allele Registry (CAR) to return VMC structures
    rather than CAR native structures.
  version: 0.0.0

servers:
  - url: http://localhost:9090/car

paths:
  /allele:
    get:
      summary: search for a canonical allele
      tags: [ClinGen]
      parameters:
        - name: hgvs
          in: query
          schema:
            type: string
          example: NC_000010.11:g.87894077C>T
      responses:
        "200":
          description: found; variation returned

  /allele/{id}:
    get:
      summary: gets a variation instance by id
      parameters:
        - name: id
          in: path
          description: canonical allele id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: found; variation returned
