openapi: 3.0.0
info:
  title: ClinGen Allele Registry wrapper
  description: >-
    Wraps the ClinGen Allele Registry (CAR) to return VMC structures
    rather than CAR native structures.
  version: 0.0.0

servers:
  - url: http://localhost:9090/car

paths:
  /ca:
    get:
      summary: search for a canonical allele
      responses:
        "200":
          description: found; variation returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variation"

  /ca/{id}:
    get:
      summary: gets a variation instance by id
      parameters:
        - name: id
          in: path
          description: canonical allele id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: found; variation returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Variation"
                

components:
  schemas:
    Variation:
      type: object
      properties:
        id:
          type: string
        type:
          type: enum
          enum: [hgvs-allele, hgvs-haplotype, hgvs-genotype, car-id, car-hgvs, vcf, rsid-alt, text]

